apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.castservice.name }}
spec:
  replicas: {{ .Values.castservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.castservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.castservice.name }}
    spec:
      containers:
        - name: {{ .Values.castservice.name }}
          image: "{{ .Values.castservice.image.repository }}:{{ .Values.castservice.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.castservice.port }}
          env:
            - name: DATABASE_URI
              value: "{{ .Values.castservice.env.DATABASE_URI }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castservice.name }}
spec:
  selector:
    app: {{ .Values.castservice.name }}
  ports:
    - port: {{ .Values.castservice.port }}
      targetPort: {{ .Values.castservice.port }}

