apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.moviedb.name }}
spec:
  replicas: {{ .Values.moviedb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.moviedb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.moviedb.name }}
    spec:
      containers:
        - name: {{ .Values.moviedb.name }}
          image: {{ .Values.moviedb.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.moviedb.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.moviedb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.moviedb.env.POSTGRES_DB }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.moviedb.name }}-storage
      volumes:
        - name: {{ .Values.moviedb.name }}-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moviedb.name }}
spec:
  selector:
    app: {{ .Values.moviedb.name }}
  ports:
    - port: {{ .Values.moviedb.port }}
      targetPort: {{ .Values.moviedb.port }}
