
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.movieservice.name }}
spec:
  replicas: {{ .Values.movieservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.movieservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.movieservice.name }}
    spec:
      containers:
        - name: {{ .Values.movieservice.name }}
          image: {{ .Values.movieservice.image }}
          ports:
            - containerPort: {{ .Values.movieservice.port }}
          env:
            - name: DATABASE_URI
              value: {{ .Values.movieservice.env.DATABASE_URI }}
            - name: CAST_SERVICE_HOST_URL
              value: {{ .Values.movieservice.env.CAST_SERVICE_HOST_URL }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.movieservice.name }}
spec:
  selector:
    app: {{ .Values.movieservice.name }}
  ports:
    - port: {{ .Values.movieservice.port }}
      targetPort: {{ .Values.movieservice.port }}