apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxservice.name }}
spec:
  replicas: {{ .Values.nginxservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nginxservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginxservice.name }}
    spec:
      containers:
        - name: {{ .Values.nginxservice.name }}
          image: {{ .Values.nginxservice.image }}
          ports:
            - containerPort: {{ .Values.nginxservice.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ .Values.nginxservice.configMapName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginxservice.name }}
spec:
  selector:
    app: {{ .Values.nginxservice.name }}
  ports:
    - port: {{ .Values.nginxservice.port }}
      targetPort: {{ .Values.nginxservice.port }}
